### ISSUE TITLE
当我运行demo_rh.py时，出现ImportError: cannot import name resnet

### ISSUE THREAD

**Issue by yzz-cver** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#10]

**Comment by yzz-cver** [comment]
![1](https://user-images.githubusercontent.com/53545589/63669888-d9758b00-c80d-11e9-9bc7-69e92a13cfaa.png)

**Comment by baokelion** [comment]
@yzz-cver resnet存在交叉引用的问题，我在另一个py文件里把全局导入resnet改成了在一个函数里导入了。

**Comment by yangxue0827** [comment]
代码已更新 @yzz-cver
