### ISSUE TITLE
在运行demo_rh.py文件时，出现restore问题

### ISSUE THREAD

**Issue by yzz-cver** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#11]

**Comment by yzz-cver** [comment]
![图片1](https://user-images.githubusercontent.com/53545589/63738978-392b6f00-c8be-11e9-8ded-07b380bfffa2.png)

**Comment by yangxue0827** [comment]
你加载的是预训练模型 @yzz-cver

**Comment by yzz-cver** [comment]
是的@yangxue0827

**Comment by yangxue0827** [comment]
demo脚本是测试用的，需要加载你训练好的权重 @yzz-cver

**Comment by yzz-cver** [comment]
意思是我先make records ,train.py后，才能运行这里的demo吗？@yangxue0827

**Comment by yangxue0827** [comment]
你可以下载我提供的训练好的权重，放在正确的位置 @yzz-cver

**Comment by yzz-cver** [comment]
![Uploading 1.png…]()
已经放在正确的位置了

**Comment by yzz-cver** [comment]
![1](https://user-images.githubusercontent.com/53545589/63739870-70e7e600-c8c1-11e9-816d-6a3b56a155d1.png)
我是下载好之后，出现的这个问题 @yangxue0827

**Comment by yangxue0827** [comment]
少了一级目录 @yzz-cver

**Comment by yzz-cver** [comment]
![微信截图_20190827124147](https://user-images.githubusercontent.com/53545589/63741533-0dad8200-c8c8-11e9-8507-585da17958fc.png)
这样？cfgs里面的路径是：TRAINED_CKPT = os.path.join(ROOT_PATH, 'output/trained_weights')
少了哪一级目录，抱歉没看出来

**Comment by yangxue0827** [comment]
放权重的那个文件夹 @yzz-cver

**Comment by yzz-cver** [comment]
![1](https://user-images.githubusercontent.com/53545589/63742235-beb51c00-c8ca-11e9-82ed-58ba7c09263a.png)
我都放在trained_weights文件夹里面了，不明白您说的是什么意思

**Comment by yangxue0827** [comment]
你下载的权重不应该是放在一个文件夹里的吗，把整个文件夹放放trained weights @yzz-cver

**Comment by yzz-cver** [comment]
![1](https://user-images.githubusercontent.com/53545589/63742797-97f7e500-c8cc-11e9-8421-3666b3ddfe01.png)
已经这样做了，还是出现一样的问题

**Comment by yangxue0827** [comment]
你是不是没调用gpu @yzz-cver

**Comment by yzz-cver** [comment]
python demo_rh.py (demo_rh_pyramid.py) --src_folder='/PATH/TO/DOTA/IMAGES_ORIGINAL/' 
                                       --image_ext='.png' 
                                       --des_folder='/PATH/TO/SAVE/RESULTS/' 
                                       --save_res=False
                                       --gpu='0'
我只是把路径改了下，其他的没动过

**Comment by yangxue0827** [comment]
我看你最先贴的那个图片上是没有调用gpu的 @yzz-cver

**Comment by yzz-cver** [comment]
之前的device没有写对，这shi是调用之后，不明白为什么还是restore
![1](https://user-images.githubusercontent.com/53545589/63746066-6edc5200-c8d6-11e9-848e-2c13563d8f32.png)

**Comment by yzz-cver** [comment]
已经跑通，感谢！
