### ISSUE TITLE
关于cfgs.SHOW_SCORE_THRSHOLD 的设置

### ISSUE THREAD

**Issue by yzz-cver** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#12]
![1](https://user-images.githubusercontent.com/53545589/63818723-fa0c2500-c974-11e9-8448-27fc5bb6980a.png)
你好，想问一下这个值该如何设置，感谢！

**Comment by yzz-cver** [comment]
DOTA的map是0.667，和论文中的map差距挺大，不知道是什么原因？

**Comment by yangxue0827** [comment]
你用哪个脚本测试的？ @yzz-cver

**Comment by yzz-cver** [comment]
我是用的
![image](https://user-images.githubusercontent.com/53545589/64085454-6c11af00-cd65-11e9-8b71-5e9230ac1e33.png)
将save_res设置为True

**Comment by yangxue0827** [comment]
要用括号里的脚本会比较好 @yzz-cver

**Comment by yzz-cver** [comment]
好的，我试下

**Comment by yzz-cver** [comment]
我用的上面那个括号里面的demo，一张图片差不多需要消耗如图所示时间，我用的一张卡，感觉好慢，是因为卡数的原因吗？![image](https://user-images.githubusercontent.com/53545589/64093132-b73db900-cd89-11e9-9e29-47dfbd77a2d6.png)
还有测试时无论save_res True 或 False 都需要设置cfgs.SHOW_SCORE_THRSHOLD  原文件该值为0.5，但save_res为False时，需要重新设定，不知道该值到底取多少合适？

**Comment by yangxue0827** [comment]
1.写个脚本是多尺度测试，我论文里的写了的image pyramid，这个脚本我没有写多gpu测试，你要快的话可以参考这个代码修改https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/test_dota.py
2.那个阈值设置是这样的，如果你要可视化，那么就需要卡一个比较高的阈值，如果你要测mAP那么就不需要卡或者卡一个很小的阈值，不然结果会偏低挺多的 @yzz-cver

**Comment by yzz-cver** [comment]
好的，谢谢
