### ISSUE TITLE
重新训练DOTA数据集，maketfrecorder时出现问题

### ISSUE THREAD

**Issue by yzz-cver** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#13]
![1](https://user-images.githubusercontent.com/53545589/63839427-de733f80-c9b1-11e9-901b-afbe75bb2169.png)

**Comment by baokelion** [comment]
我训练dota的时候，也出现类似的问题

**Comment by yangxue0827** [comment]
检查tfrecord @yzz-cver @baokelion

**Comment by baokelion** [comment]
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]
我出现这个错误也是tfrecord的问题嘛？ @yangxue0827

**Comment by yangxue0827** [comment]
大概率是的 @baokelion
