### ISSUE TITLE
make_anchors的ws和hs的代码bug问题

### ISSUE THREAD

**Issue by congjianting** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#14]
@yangxue0827 @yangJirui 

代码中的,
ws, hs = enum_ratios(enum_scales(base_anchor, anchor_scales),
                             anchor_ratios)  # per locations ws and hs

子函数的返回值是hs,ws, 这里是不是写错了?

def enum_ratios(anchors, anchor_ratios):
    '''
    ratio = h /w
    :param anchors:
    :param anchor_ratios:
    :return:
    '''
    ws = anchors[:, 2]  # for base anchor: w == h
    hs = anchors[:, 3]
    sqrt_ratios = tf.sqrt(tf.constant(anchor_ratios))

    ws = tf.reshape(ws / sqrt_ratios[:, tf.newaxis], [-1, 1])
    hs = tf.reshape(hs * sqrt_ratios[:, tf.newaxis], [-1, 1])

    return hs, ws

**Comment by yangxue0827** [comment]
是有问题，不过不影响结果 @congjianting

**Comment by congjianting** [comment]
这个是因为你的问题都是对称配置的参数吗？


 
---原始邮件---
发件人: "yangxue"<notifications@github.com&gt;
发送时间: 2019年9月16日(星期一) 晚上7:25
收件人: "DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow"<R2CNN-Plus-Plus_Tensorflow@noreply.github.com&gt;;
抄送: "congjianting"<747544227@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow] make_anchors的ws和hs的代码bug问题 (#14)



是有问题，不过不影响结果 @congjianting
