### ISSUE TITLE
用python3需要改那些代码

### ISSUE THREAD

**Issue by S130111** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#15]

**Comment by yangxue0827** [comment]
基本不用怎么改

**Comment by S130111** [comment]
谢谢啦





| |
13011195230
|
|
邮箱：13011195230@163.com
|

Signature is customized by Netease Mail Master

在2019年09月16日 19:24，yangxue 写道：

基本不用怎么改
