### ISSUE TITLE
DOTA数据集训练失败

### ISSUE THREAD

**Issue by yu1206** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#17]
你好，用DOTA数据集进行训练时，到step300 就卡到这里了，不再往下训练了，卡了一个晚上不动。。是什么原因引起的？ 训练过程如下
2019-09-11 19:35:25: step200    image_name:b'P0000_4352_0512.png' |
                                                   rpn_loc_loss:0.004083531908690929 |  
                                               rpn_cla_loss:0.4112159013748169 |
                                                   rpn_total_loss:0.4152994453907013 |
                                                   fast_rcnn_loc_loss:0.2768683433532715 |      
                                                  fast_rcnn_cla_loss:0.07029825448989868 |
                                                   fast_rcnn_loc_rotate_loss:0.46062421798706055 |  
                                                 fast_rcnn_cla_rotate_loss:0.07179155200719833 |
                                                   fast_rcnn_total_loss:0.879582405090332 |     
                                                   attention_loss:0.11331246793270111 |
                                                   total_loss:1.9829115867614746 |      
                                                  pre_cost_time:1.2178001403808594s
2019-09-11 19:39:05: step300    image_name:b'P0002_1280_0000.png' |
                                                   rpn_loc_loss:0.002683267230167985 |  
                                                  rpn_cla_loss:0.571774959564209 |
                                                   rpn_total_loss:0.5744582414627075 |
                                                   fast_rcnn_loc_loss:0.6731187105178833 |      
                                                   fast_rcnn_cla_loss:0.556395947933197 |
                                                   fast_rcnn_loc_rotate_loss:1.3842848539352417 |   
                                                      fast_rcnn_cla_rotate_loss:0.5610043406486511 |
                                                   fast_rcnn_total_loss:3.1748037338256836 |    
                                                    attention_loss:0.22223511338233948 |
                                                   total_loss:4.546215534210205 |       
                                                    pre_cost_time:1.202199935913086s

**Comment by yangxue0827** [comment]
检查一下tfrecord吧
