### ISSUE TITLE
您好，我看到您的code里把inception module给注释掉了？

### ISSUE THREAD

**Issue by Keysmis** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#18]
您好，我看到您的code里把inception module给注释掉了？会对结果造成什么影响吗？我的应用场景是textdetection～
谢谢～

**Comment by yangxue0827** [comment]
是我提供的那个权重的问题，我只找到不用inception module的权重，影响不大的 @Keysmis
