### ISSUE TITLE
train model 能直接使用吗？

### ISSUE THREAD

**Issue by zhouzhubin** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#19]
@yangxue0827 你好，请问你提供的 train model可以直接使用吗？我用你给的，在demo_rh.py保存的检测图片，发现，都是不行的，检测不到的，请问是不是自己重新训练才行？？

**Comment by yangxue0827** [comment]
可以用的，你检查一下是否放对位置，你可能是由于位置放的不对没加载上这个权重 @zhouzhubin

**Comment by zhouzhubin** [comment]
@yangxue0827 恩恩，谢谢了啊！是我把路径搞错了，少建了一个文件夹。我还一个疑问，这里输出的是中心点，w，h，theta（-90，0），是不是不能知道被检测目标的具体朝向了？

**Comment by yangxue0827** [comment]
不能，要知道朝向就需要360的定义了 @zhouzhubin

**Comment by zhouzhubin** [comment]
恩恩，好的，太感谢了 @yangxue0827

**Comment by zhouzhubin** [comment]
@yangxue0827 你好，我想问一下，预测中心点，w，h，theta（-90，0）的loss就是用了smooth_l1吗？我如果在数据处理的时候，直接将预测的x，y替换成起始点的x0，y0。这样就可以得到起始点坐标了，可以这样操作吗？

**Comment by zhouzhubin** [comment]
@yangxue0827 大佬你好，如果我直接将theta替换成（x0,y0）和（x3，y3）与x轴向量夹角的话，theta的范围是（-180,180），这样训练会有影响吗？比如iou的计算会不会有影响？

**Comment by yangxue0827** [comment]
这个你得自己写脚本测试，我也不清楚。如果你要达到的目的是知道目标的具体方向，你可以参考这个repo的做法https://github.com/yangxue0827/R2CNN_HEAD_FPN_Tensorflow.git，但是这个repo的FPN基础代码没复习好，可能需要你自己进行移植。 @zhouzhubin

**Comment by zhouzhubin** [comment]
恩恩，好的，谢谢了 @yangxue0827 我去看一下这个代码。
