### ISSUE TITLE
dota数据训练，内存溢出？

### ISSUE THREAD

**Issue by yu1206** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#22]
用dota 1411张图片按照代码裁剪800*800的子图，有 55178个子图。转成tfrecord有98.4G。训练内存溢出了，应该减少训练图片个数还是修改cfg.py 的那些参数？
FIXED_BLOCKS = 2  # allow 0~3，
IMG_SHORT_SIDE_LEN = [800, 600, 700, 900, 1000, 1100, 1200]，
IMG_MAX_LENGTH = 1000，
RPN_MINIBATCH_SIZE = 512，
是修改这些参数么？

**Comment by yangxue0827** [comment]
对的，根据你gpu显存来设置图片大小 @yu1206
