### ISSUE TITLE
请问widows10下编译报这个错，有谁知道怎么解决吗？

### ISSUE THREAD

**Issue by Beam-wi** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#25]
PS F:\PycharmProjects\R2CNN-Plus-Plus_Tensorflow-master\libs\box_utils> python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 47, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by Beam-wi** [comment]
@yangxue0827 作者你好  我在win10上 用你的工程  编译的时候出现蛮多问题  请问这个有wins方面的解决办法吗？

**Comment by yangxue0827** [comment]
我实在linux系统下做的，最简单的方式是你自己用tf或者numpy写一个IoU函数替换这个C的代码 @Beam-wi
