### ISSUE TITLE
IoU smooth-l1 loss function

### ISSUE THREAD

**Issue by yzheng97** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#26]
It seems that the implementation of IoU smooth-l1 loss mentioned in the paper is missing in this repo. While it is implemented in https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/b03a7eafba21bfbb78dbffe1be53ab914080201e/libs/losses/losses.py#L139

**Comment by yangxue0827** [comment]
The early paper was called R2CNN++, which did not include IoU-smooth loss. I built another [repo](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation) to verify it separately. @yzheng97
