### ISSUE TITLE
你好 ，我想问一下论文里的image pyramid是怎么做的

### ISSUE THREAD

**Issue by zccheng123** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#3]
论文里的scale the original image to 600,800,1000,1200。这一步是指将图片切分为600*600\800*800这样不同的大小，送入网络；还是我先讲图片切成800*800，然后resize成不同大小，还是我将图片切成1200*1200再resize，或者其他方法。

**Comment by yangxue0827** [comment]
我是先将图片切成800800，然后resize成不同大小 @zccheng123
