### ISSUE TITLE
low ap

### ISSUE THREAD

**Issue by lijain** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#38]
When I run vaild data of DOTA with the weight of demo_rh.py and R2CNN_20180922_DOTA_v28 given by the author, why are some categories of AP still relatively low?

**Comment by yangxue0827** [comment]
try [demo_rh_pyramid.py](https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow/blob/master/tools/demo_rh_pyramid.py)
@lijain

**Comment by lijain** [comment]
ok,I try




------------------ 原始邮件 ------------------
发件人: "yangxue"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午2:55
收件人: "DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow"<R2CNN-Plus-Plus_Tensorflow@noreply.github.com>;
抄送: "利剑"<1632401541@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow] low ap (#38)




Closed #38.

**Comment by yangxue0827** [comment]
It may be very slow, it is recommended to use multi-gpu test, reference [code](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/test_dota.py).
@lijain

**Comment by lijain** [comment]
The test? Dota.py file can't be used directly





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yangxue"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 下午3:03
收件人:&nbsp;"DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow"<R2CNN-Plus-Plus_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow] low ap (#38)




It may be very slow, it is recommended to use multi-gpu test, reference code.
 @lijain
