### ISSUE TITLE
Details about IoU-smooth L1 loss.

### ISSUE THREAD

**Issue by cool-xuan** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#41]
In your paper, you propose a noval regression loss called IoU-smooth L1 loss, which make a big deal in performance. But in your  code I have no idea what is the IoU-smooth L1 loss. Coulde you give some more detailed illumination about this, Thanks a lot.

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation
@cool-xuan
