### ISSUE TITLE
大佬，请问你训练一次要多长时间？

### ISSUE THREAD

**Issue by Bennett-Yang** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#44]
论文里面写你们用的是1080是嘛？我也是。 我训练了一天两夜还没训练完，不知道是出了问题还是确实需要这么长时间，特向大佬求教，谢谢。

**Comment by yangxue0827** [comment]
建议多gpu训练，参考代码：https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/multi_gpu_train.py
@Bennett-Yang

**Comment by Bennett-Yang** [comment]
> 建议多gpu训练，参考代码：https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/multi_gpu_train.py
> @Bennett-Yang

谢谢大佬

**Comment by xiaozhen18239228065** [comment]
@Bennett-Yang ,请问可以参考一下您的多卡训练代码吗，我写的有些问题

**Comment by yangxue0827** [comment]
推荐使用https://github.com/yangxue0827/RotationDetection
