### ISSUE TITLE
It's just a simple question about enviroment

### ISSUE THREAD

**Issue by HMCBSJ** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#45]
Basically, Is Installing Caffe on Linux recommended to run the code as a must step for running Fast RCNN here? Thanks!!

**Comment by yangxue0827** [comment]
this a tensorflow based repo. @HMCBSJ

**Comment by HMCBSJ** [comment]
Thanks for your reply! Actually, I was having a problem while compiling setup.py on  libs\box_utils. I am using Window.
Here is the error script
python setup.py build_ext --inplace
home = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0

{'lib64': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\lib\\x64', 'nvcc': 'C:\\Program Fil
es\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin\\nvcc.exe', 'include': 'C:\\Program Files\\NVIDIA GPU Com
puting Toolkit\\CUDA\\v9.0\\include', 'home': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0'
}
running build_ext
skipping 'rotate_polygon_nms.cpp' Cython extension (up-to-date)
building 'rotate_polygon_nms' extension
**error: Don't know how to compile rotate_polygon_nms_kernel.cu to build\temp.win-amd64-3.5\Release\rotate_polygon_nms_kernel.obj**

I was searching for a solution.  and found this answer " https://github.com/rbgirshick/py-faster-rcnn/issues/615 ". It was most similar situation with mine. and the comment for the problem was trying Caffe. 

I think I am missing some basic installation for compiling faster RCNN. 
Do you have any Idea, telling me OS environment also will help alot! 
Thanks!

**Comment by yangxue0827** [comment]
You need Linux. @HMCBSJ
