### ISSUE TITLE
when SCRDet code will be released?

### ISSUE THREAD

**Issue by helloxueen** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#48]
hi ,Xue Yang, when SCRDet code will be released?

**Comment by ibrahimsoliman97** [comment]
I have noticed that his code includes the implementation of SCRDet, but these parts are commented.
I am not sure, is will it work, if we uncomment and train again.
But for sure, the available pretrained weight is for current version that does not include the SCRDet implementation.

**Comment by yangxue0827** [comment]
you can use it @ibrahimsoliman97 @

**Comment by helloxueen** [comment]
but there doesn't exist roialign code in this version.

**Comment by helloxueen** [comment]
but there doesn't exist roialign code in this version.

> 
> 
> you can use it @ibrahimsoliman97 @

but there doesn't exist roialign code in this version.

**Comment by ibrahimsoliman97** [comment]
@helloxueen You are correct, i have not noticed that at beginning. There is only ROI Pooling in this implementation while the paper mentioned ROI Align method.

@yangxue0827  we hope if you could provide some elaboration about it. Many thanks for your efforts.

**Comment by yangxue0827** [comment]
[tf.image.crop_and_resize](https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow/blob/master/libs/networks/layer.py#L55) is roi align, refer [here](https://zhuanlan.zhihu.com/p/65467789).

I made the wrong function name, my fault.
@helloxueen @ibrahimsoliman97

**Comment by ibrahimsoliman97** [comment]
Understood.
Thanks for your reply and elaboration.
@yangxue0827
