### ISSUE TITLE
Requesting information about SCRDet implementation

### ISSUE THREAD

**Issue by ibrahimsoliman97** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#49]
Thanks for publishing this repository.

After studying your code, i have noticed that the implementation of SCRDet is existed in your code, but it is commented. For example, current code and pretrained weight have many parts stated in your paper (SCRDet) as (SF-Net C3-UPsampling and Inception Module) and (MDA-Net Channel attention) are commented.

My question is: can i uncomment all these parts and train on DOTA or ICDAR dataset using the full SCRDet implementation?

**Comment by yangxue0827** [comment]
Yes, you can. @ibrahimsoliman97
