### ISSUE TITLE
ap==0

### ISSUE THREAD

**Issue by lijain** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#55]
When I test the Val data of DOTA with eval.py, where
cls : swimming-pool|| Recall: 0.0 || Precison: 0.0|| AP: 0.0
I used the weight you gave me

**Comment by yangxue0827** [comment]
We recommend using demo_rh_pyramid.py or demo_rh.py for dota dataset. If you really want to use eval.py, you need to modify [Line75 ](https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow/blob/master/tools/eval.py#L75) (feed_dict={img_plac: raw_img} --> feed_dict={img_plac: raw_img[:, :, ::-1]})

@lijain
