### ISSUE TITLE
soomthl1-iou

### ISSUE THREAD

**Issue by lijain** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#58]
Does the smooth L1 loss in this algorithm include IOU?

**Comment by yangxue0827** [comment]
No, iou-smooth l1 loss is in https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation
@lijain

**Comment by lijain** [comment]
ok,thanks

**Comment by a5372935** [comment]
@lijain would you add iou factor in SCRDet?
