### ISSUE TITLE
Getting empty prediction on trained model

### ISSUE THREAD

**Issue by lamhoangtung** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#59]
Hi @yangxue0827. Thanks for the amazing work!

I have tried to follow your instruction in the README file to test the pretrained model but I always get empty result from it.

I have tried the inference.py, demo_rh.py and demo_rh_pyramid.py script but the result are still empty like this:

![P1960_0000_0684_h](https://user-images.githubusercontent.com/26834698/71706601-90b38b80-2e18-11ea-93d9-f33151a7e586.jpg)

The SHOW_SCORE_THRSHOLD value inside config is 0.5 because I turn on save res.

Am I wrong at any step ? Can you help me out a little bit here. Thanks a lot

**Comment by yangxue0827** [comment]
pretrained model is used for training, you need download trained weights for prediction (demo_rh.py or demo_rh_pyramid.py for DOTA dataset). @lamhoangtung

**Comment by lamhoangtung** [comment]
> pretrained model is used for training, you need download trained weights for prediction (demo_rh.py or demo_rh_pyramid.py for DOTA dataset). @lamhoangtung

Thanks for your reply. I already downloaded the trained model at https://drive.google.com/file/d/1079vPatiJCfUImhGdfCA0EGUgumzzKPI/view 

![image](https://user-images.githubusercontent.com/26834698/71707233-5ac3d680-2e1b-11ea-8bc9-51cdcaf3bc78.png)

as your instruction in the README file

**Comment by yangxue0827** [comment]
recommand this [script ](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/test_dota.py)for DOTA test, which support multi-gpu test.

**Comment by yangxue0827** [comment]
trained weight path refer [here](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/51) @lamhoangtung

**Comment by lamhoangtung** [comment]
@yangxue0827 So I just need to swap the test script from that repo into this repo and it will work ?

**Comment by yangxue0827** [comment]
You need to make some changes. The test script for that repo will be faster, but this one is also available.

**Comment by lamhoangtung** [comment]
> trained weight path refer [here](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/51) @lamhoangtung
> ![image](https://user-images.githubusercontent.com/29257168/71707409-a169fe80-2e24-11ea-8104-495379b4a5d7.png)

Thanks for your help. Is this how I should put the trained model for this repo too ?

**Comment by yangxue0827** [comment]
RetinaNet_DOTA_1x_20190607 is just an example, what exactly depends on the name of the compressed package you downloaded.

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/71707597-c317b580-2e25-11ea-82e8-7a3cdc31ca2f.png)

**Comment by lamhoangtung** [comment]
Got it. Thanks for your help. I will report back soon

**Comment by lamhoangtung** [comment]
> trained weight path refer [here](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/51) @lamhoangtung
> ![image](https://user-images.githubusercontent.com/29257168/71707409-a169fe80-2e24-11ea-8104-495379b4a5d7.png)

Just make sure to put the model like this and it will work. Thanks a lot for your help @yangxue0827
