### ISSUE TITLE
测试训练的模型，swimming-pool的ap=0.0013

### ISSUE THREAD

**Issue by baokelion** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#6]
用demo.py进行了测试，数据集是dota的val，并且进行了val_crop.py裁剪，用dota_devkit中的测试脚本进行了测试，测试结果如下：
classname: plane
ap:  0.8043356143149806

classname: baseball-diamond
ap:  0.7632814847658935

classname: bridge
ap:  0.45506307334937024

classname: ground-track-field
ap:  0.6750099483352051

classname: small-vehicle
ap:  0.5591377615596839

classname: large-vehicle
ap:  0.6746200558900223

classname: ship
ap:  0.6556901466589511

classname: tennis-court
ap:  0.9075544170664117

classname: basketball-court
ap:  0.7445786918243077

classname: storage-tank
ap:  0.6838217965433654

classname: soccer-ball-field
ap:  0.5940273758469495

classname: roundabout
ap:  0.7472942076726852

classname: harbor
ap:  0.7384752552414509

classname: swimming-pool
ap:  0.0013568521031207597

classname: helicopter
ap:  0.5403029396351005

map: 0.6363033080538332
其中swimming-pool得分只有0.13，但是作者测试的数据是63，了解作者测试的数据集是dota的test集，并且提交的官方系统，不过测试集的影响应该不大。我并没有对cfgs进行参数修改。请问这个异常如何解决呢？

**Comment by yangxue0827** [comment]
直接运行demo.py或者demo_rh_pyramid.py，不需要用到val_crop.py脚本，代码里自己会裁剪的。 @baokelion

**Comment by baokelion** [comment]
@yangxue0827 多谢，重新测试了一遍，和作者的结果接近。
[90.47587619 81.23856231 49.88258828 82.80497012 55.28739461 68.45812141
 65.76273789 90.84134941 77.4608252  88.28769706 88.06057288 74.66922825
 77.03443748 68.18969188 74.89241408]

**Comment by lijain** [comment]
I also tested it with the demo? Rh? Pyramid.py script, but the map was also 0.63 instead of 0.75. How did you test it?
