### ISSUE TITLE
Change batch size for training

### ISSUE THREAD

**Issue by chongyeh** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#62]
Hi, I would like to know how to change the batch size for training. It gives this error when I try to change the batch size to 8.

ValueError: Can not squeeze dim[0], expected a dimension of 1, got 8 for 'get_batch/Squeeze_1' (op: 'Squeeze') with input shapes: [8,?,9].

**Comment by alexshaodong** [comment]
> Hi, I would like to know how to change the batch size for training. It gives this error when I try to change the batch size to 8.
> 
> ValueError: Can not squeeze dim[0], expected a dimension of 1, got 8 for 'get_batch/Squeeze_1' (op: 'Squeeze') with input shapes: [8,?,9].

Hello! Have you solved the problem? The same thing happened to me. Thank you!

**Comment by yangxue0827** [comment]
batch size ＞1 is not support

**Comment by alexshaodong** [comment]
> batch size ＞1 is not support

So I can only set batch_size to 1, right? I see the batch_size in the source code is 2 or 4, and the code i run is e3d-lstm.

**Comment by yangxue0827** [comment]
this repo only support bs=1
