### ISSUE TITLE
Attention部分好像和论文描述不太一样？

### ISSUE THREAD

**Issue by Bennett-Yang** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#67]
论文中，MDA-Net部分有两个通道，pixel attention的部分有Inception模块。但是我读了代码之后，发现attention.py这个文件中只有build_attetion这个函数被调用过，其他函数并没有被调用。而build_attetion这个函数也只是五层卷积，并没有使用Inception的结构。请问是我理解有误，还是作者出于什么样的考量没有采用原文所说的结构呢？谢谢！

**Comment by yangxue0827** [comment]
因为我只找到这版本的训练好的权重，你要是想用原文的，在相应的地方我只是注释了而已，你替换一下自己训练一个就行。

**Comment by yangxue0827** [comment]
在resnet.py的151行

**Comment by Bennett-Yang** [comment]
这样啊，知道了。谢谢！
