### ISSUE TITLE
关于attention loss的问题

### ISSUE THREAD

**Issue by LaserLV52** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#69]
你好，我看到代码和论文中在pixel attention部分都有相关表述，就是特征图进来之后先经过一个inception，之后通过卷积变成一个w*h*2的特征图，attention loss是用这个两通道的特征图计算的，就是不太清楚这里为什么需要2个通道呢？
我进一步查看build_attention_loss相关代码，发现这里用两个通道是因为mask标签是两个通道的？但是mask为什么要两个通道呢，mask不是一个二值标签吗，用0，1表示背景和前景不需要两个通道呀，我是遗漏了什么吗？

**Comment by yangxue0827** [comment]
用onehot编码分类的时候，就需要预测两个通道。

**Comment by LaserLV52** [comment]
> 用onehot编码分类的时候，就需要预测两个通道。

意思就是前景和背景相当于是两个类别了，就要两个通道了是吧？只不过在网络主干里面pixel attention的时候，因为前景和背景是互补的，只需要取第一个通道表示前景，乘进原始特征图里面就有pixel attention的效果了对吧。
但是计算attention loss的时候就用前景和背景两个类别一起算损失了是吧？前景和背景都用来计算损失的原因是这样的supervision会更强吗？因为我的理解前景和背景都互补了，算损失的话我只算其中一个不是也可以吗？

**Comment by yangxue0827** [comment]
就像rpn也是前后景的分类，用两个维度只是实现上更容易方便，有没有额外的作用我不太清楚。原理上，单类分类，预测一个通道和两个通道都是可以的，我觉得没必要纠结。




| |
杨学
|
|
邮箱：yangxue0827@126.com
|

签名由 网易邮箱大师 定制

在2020年06月10日 11:35，XH 写道：

用onehot编码分类的时候，就需要预测两个通道。

意思就是前景和背景相当于是两个类别了，就要两个通道了是吧？只不过在网络主干里面pixel attention的时候，因为前景和背景是互补的，只需要取第一个通道表示前景，乘进原始特征图里面就有pixel attention的效果了对吧。
但是计算attention loss的时候就用前景和背景两个类别一起算损失了是吧？前景和背景都用来计算损失的原因是这样的supervision会更强吗？因为我的理解前景和背景都互补了，算损失的话我只算其中一个不是也可以吗？

**Comment by LaserLV52** [comment]
> 就像rpn也是前后景的分类，用两个维度只是实现上更容易方便，有没有额外的作用我不太清楚。原理上，单类分类，预测一个通道和两个通道都是可以的，我觉得没必要纠结。 | | 杨学 | | 邮箱：yangxue0827@126.com | 签名由 网易邮箱大师 定制 在2020年06月10日 11:35，XH 写道： 用onehot编码分类的时候，就需要预测两个通道。 意思就是前景和背景相当于是两个类别了，就要两个通道了是吧？只不过在网络主干里面pixel attention的时候，因为前景和背景是互补的，只需要取第一个通道表示前景，乘进原始特征图里面就有pixel attention的效果了对吧。 但是计算attention loss的时候就用前景和背景两个类别一起算损失了是吧？前景和背景都用来计算损失的原因是这样的supervision会更强吗？因为我的理解前景和背景都互补了，算损失的话我只算其中一个不是也可以吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯 现在明白了，谢谢。原理上应该是没什么区别的。
