### ISSUE TITLE
Error in  train phase

### ISSUE THREAD

**Issue by ztyxd** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#7]
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

I have this error when i train the model, i use the default cfgs, can u give some suggestions?

**Comment by Baby47** [comment]
I have encountered the same question as you and  i have changed the default cfgs, I wonder how you solved this problem ,thanks very much .@ztyxd

**Comment by wenliangsun** [comment]
@Baby47  you should provide that the name of tf_record is same between the cfg.py and your tf_record

**Comment by xiangzhang06** [comment]
I have encountered the same question as you, I wonder how you solved this problem ,thanks very much . @ztyxd @wenliangsun @Baby47
