### ISSUE TITLE
Roughly solve the problem of rotating box

### ISSUE THREAD

**Issue by a5372935** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#72]
簡單說一下我利用了此方法加上我自製的exp(IoU)使得旋轉框問題有明顯降低，但仍然還是有5~10%會出現偏移的狀況，或許是因為你說的角度週期性以及長寬比例的縮放，我和我的教授討論了許久，並嘗試解決此問題，最後我嘗試在coordinate_convert.py裡面固定了ground truth的長寬，也就是說固定長短邊，長邊w，短邊h，要是 h > w 則做交換動作角度也加上90度，在實驗結果出乎意料地不錯。在此我想跟你討論，是否是因為RPN產出的proposal與ground truth非常相關，也就是說proposal的框大致是參考ground truth使得預測結果在長方形的框幾乎不會出現偏移的狀況，但在框要是接近正方形偏移的情形其實還是有。

**Comment by a5372935** [comment]
我在支乎那邊沒辦法回復你><

**Comment by yangxue0827** [comment]
你好，你提到的exp(iou)和长边定义法我都在另一个retinanet_tensorflow_rotation做了实验的，对边界问题都是有很好帮助的，进一步讨论你可以加我微信，yangxue-0826 @a5372935

**Comment by yangxue0827** [comment]
exp(iou)iou是在r3det那个repo，这个函数比较稳定不容易nan

**Comment by a5372935** [comment]
我加微信了˙
