### ISSUE TITLE
map

### ISSUE THREAD

**Issue by yzk-lab** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#74]
why the  ap  of  swimming pool is so low ?while  other ap is normal  close  to the  result  served by the author .my  swimming pool's ap is just 0.007.i have tried   changes  three times  including  rectify the dataset  and parameters . what's the reason? i don't understand.

**Comment by yangxue0827** [comment]
This is caused by the inconsistency of the image channel order of training and testing. It is recommended that you reverse the image channel when testing, such as img[:, :, ::-1] @yzk-lab

**Comment by yzk-lab** [comment]
thanks for your reply.But I found the channel in the  demo.py is already  img[:,:,::-1],what changes should i make? I know a little with the  object detection .I hope you  can direct me more.Thanks.

**Comment by yangxue0827** [comment]
if img[:,:,::-1] in demo.py, use img instead. @yzk-lab

**Comment by yzk-lab** [comment]
thanks for your reply .I have received your proposal and use the img instead.The ap of swimming pool increased  from 0.007 to 0.62.But the other ap decreased  a lot. so the average ap is less than the before.Dear anthor,what other changes i can try to increase the ap of the swimming along with the map? I hope for your reply.thanks a lot.
