### ISSUE TITLE
In pixel attention,how do you choose one of the channels in the saliency map?

### ISSUE THREAD

**Issue by Vickeyhw** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#8]
It seems that you randomly choose one of the two channel in code,why?thank you

**Comment by abcxs** [comment]
I also have this confusion, it seems that you select the first channel, why not use the second channel according to the loss function?

**Comment by yangxue0827** [comment]
Any dimension can be used as long as it can expand the feature response of the foreground and background.

@Vickeyhw @abcxs
