### ISSUE TITLE
使用dota原图进行训练，内存溢出该如何调整呢？

### ISSUE THREAD

**Issue by baokelion** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#9]
请问您是用原图进行训练的还是裁剪之后的？如果内存溢出，哪些参数可以调整呢？

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow/blob/master/libs/configs/cfgs.py#L69

减少大尺寸测试
